# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-02 04:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deudas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Deudas',
            new_name='Deuda',
        ),
        migrations.RenameModel(
            old_name='Deudor',
            new_name='Deudore',
        ),
        migrations.RenameField(
            model_name='deuda',
            old_name='Deudor',
            new_name='Deudore',
        ),
    ]
